import {useEffect,useState} from 'react';
import {Store,Search,ShoppingBag,UserRound,ArrowRight,ArrowUpRight,Plus,Minus,X,Package,Shirt,Sparkles,MapPin,CheckCircle2,Truck,LogOut,Heart,SlidersHorizontal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Toaster,toast} from 'sonner';
const money=(n:number)=>new Intl.NumberFormat('en-LK',{style:'currency',currency:'LKR',maximumFractionDigits:2}).format(n||0);
const fmt=(s:string)=>new Date(s).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'});
async function api(path:string,options?:RequestInit){const r=await fetch(path,{cache:'no-store',...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to complete this action');return d}
const post=(path:string,data:any,headers:any={})=>api(path,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify(data)});
function Art({p,index=0}:any){const src=p.images?.[index];return src?<img src={src} alt={`${p.name}${index?' — image '+(index+1):''}`} loading="lazy" onError={e=>{e.currentTarget.style.opacity='.25'}}/>:<div className={`market-placeholder ${p.category==='Cosmetics'?'blush':'linen'}`}>{p.category==='Cosmetics'?<Sparkles/>:<Shirt/>}<span>{p.category||'ShopLink'}</span></div>}
export default function Storefront(){
 const [products,setProducts]=useState<any[]>([]),[user,setUser]=useState<any>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('all'),[shop,setShop]=useState('all'),[sort,setSort]=useState('newest'),[view,setView]=useState(new URLSearchParams(window.location.search).get('view')||'browse');
 const [cart,setCart]=useState<any[]>(()=>{try{const c=JSON.parse(localStorage.getItem('shoplink-cart')||'[]');return Array.isArray(c)?c.filter(x=>typeof x.key==='string'&&Number.isInteger(x.qty)&&x.qty>0):[]}catch{return[]}}),[cartOpen,setCartOpen]=useState(false),[detail,setDetail]=useState<any>(null),[imageIndex,setImageIndex]=useState(0),[checkout,setCheckout]=useState(false),[delivery,setDelivery]=useState<any>({}),[checkoutId,setCheckoutId]=useState(''),[busy,setBusy]=useState(false),[orders,setOrders]=useState<any[]>([]),[ordersError,setOrdersError]=useState(''),[orderDetail,setOrderDetail]=useState<any>(null),[cancelOrder,setCancelOrder]=useState<any>(null);
 const loadCatalog=async()=>{try{const d=await api('/api/store/catalog');setProducts(d.products);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 const loadOrders=async()=>{setOrdersError('');try{const d=await api('/api/store/orders');setOrders(d.orders)}catch(e:any){setOrdersError(e.message)}};
 useEffect(()=>{loadCatalog();api('/api/auth/session?kind=customer').then(d=>setUser(d.user)).catch(()=>{});const t=setInterval(loadCatalog,30000);return()=>clearInterval(t)},[]);
 useEffect(()=>{localStorage.setItem('shoplink-cart',JSON.stringify(cart))},[cart]);
 useEffect(()=>{if(view==='orders'&&user){loadOrders();const t=setInterval(loadOrders,30000);return()=>clearInterval(t)}},[view,user]);
 const categories=Array.from(new Set(products.map(p=>p.category))).sort();const shops=Array.from(new Map(products.map(p=>[p.business_id+':'+p.shop_id,{id:p.business_id+':'+p.shop_id,name:p.shop_name}])).values());
 let visible=products.filter(p=>(category==='all'||p.category===category)&&(shop==='all'||shop===p.business_id+':'+p.shop_id)&&(!query||`${p.name} ${p.shop_name} ${p.description} ${p.brand}`.toLowerCase().includes(query.toLowerCase())));
 visible=[...visible].sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:sort==='name'?a.name.localeCompare(b.name):b.updated.localeCompare(a.updated));
 const lines=cart.map(c=>({...c,product:products.find(p=>p.key===c.key)}));const subtotal=lines.reduce((a,c)=>a+(c.product?.price||0)*c.qty,0),tax=lines.reduce((a,c)=>a+(c.product?.price||0)*c.qty*(c.product?.tax_rate||0)/100,0);const invalid=lines.some(c=>!c.product||c.qty>c.product.stock);const units=cart.reduce((a,c)=>a+c.qty,0);
 function add(p:any){const n=cart.find(c=>c.key===p.key)?.qty||0;if(n>=p.stock){toast.error('No more stock available');return}setCart(c=>c.some(x=>x.key===p.key)?c.map(x=>x.key===p.key?{...x,qty:x.qty+1}:x):[...c,{key:p.key,qty:1,name:p.name}]);toast.success('Added to your bag')}
 function startCheckout(){if(!user){window.location.href='/login';return}setDelivery({name:user.full_name,phone:user.phone,address:user.address});setCheckoutId(crypto.randomUUID());setCheckout(true)}
 const detailNow=detail?products.find(p=>p.key===detail.key)||detail:null;
 return <div className="market"><Toaster richColors/><div className="market-announcement"><span>Independent shops. One connected marketplace.</span></div><header className="market-header"><a className="market-brand" href="/"><span><Store size={23}/></span>ShopLink<span className="market-brand-tag">MARKET</span></a><div className="market-search"><Search size={18}/><Input aria-label="Search products or shops" placeholder="Find something you'll love…" value={query} onChange={e=>{setQuery(e.target.value);setView('browse')}}/></div><div className="market-header-actions"><button onClick={()=>{if(user)setView('orders');else window.location.href='/login'}}><Package size={19}/><span>Orders</span></button><button className="market-profile-button" aria-label="My profile" onClick={()=>setView('profile')}><UserRound size={21}/><span>My profile</span></button>{!user&&<a className="market-signup-link" href="/signup">Sign up</a>}<button onClick={()=>setCartOpen(true)} aria-label={`Shopping bag with ${units} items`}><ShoppingBag size={20}/><span>Bag</span><b>{units}</b></button></div></header><nav className="market-nav"><button className={view==='browse'?'active':''} onClick={()=>setView('browse')}>Discover</button>{categories.slice(0,5).map(c=><button className={category===c&&view==='browse'?'active':''} key={c} onClick={()=>{setCategory(c);setView('browse')}}>{c}</button>)}</nav>
 <main className="market-main">
 {view==='browse'&&<><section className="market-intro"><div><p className="eyebrow">GOOD FINDS. LOCAL ROOTS.</p><h1>A little closer<br/>to your favourites.</h1><p>Everyday essentials and special finds from independent shops.<br className="desktop"/> Browse what’s available, straight from the shop’s inventory.</p><div className="market-intro-note"><span className="status-dot"/>Current stock from every connected shop</div></div><div className="market-feature"><div className="feature-tile feature-textile"><Shirt strokeWidth={1}/><span>Style for every day</span><b>Textiles & fashion</b></div><div className="feature-tile feature-beauty"><Sparkles strokeWidth={1}/><span>Your daily ritual</span><b>Beauty & cosmetics</b></div></div></section>
 <section className="market-catalog"><div className="market-section-heading"><div><p className="eyebrow">THE COLLECTION</p><h2>Find your next favourite</h2></div><span>{visible.length} products · {shops.length} shops</span></div><div className="market-filters"><Tabs value={category} onValueChange={setCategory}><TabsList><TabsTrigger value="all">All items</TabsTrigger>{categories.map(c=><TabsTrigger value={c} key={c}>{c}</TabsTrigger>)}</TabsList></Tabs><div><Select value={shop} onValueChange={setShop}><SelectTrigger aria-label="Filter by shop"><Store size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All shops</SelectItem>{shops.map(s=><SelectItem value={s.id} key={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={sort} onValueChange={setSort}><SelectTrigger aria-label="Sort products"><SlidersHorizontal size={15}/><SelectValue/></SelectTrigger><SelectContent><SelectItem value="newest">Recently updated</SelectItem><SelectItem value="low">Price: low to high</SelectItem><SelectItem value="high">Price: high to low</SelectItem><SelectItem value="name">Name: A–Z</SelectItem></SelectContent></Select></div></div>
 {error&&<div className="error-banner" role="alert">Unable to refresh products: {error}<Button variant="outline" onClick={loadCatalog}>Retry</Button></div>}
 {loading?<div className="empty"><ShoppingBag/><b>Loading the collection…</b></div>:!visible.length?<div className="market-empty"><Package size={40}/><h3>{products.length?'No items match your search':'The collection is coming together'}</h3><p>{products.length?'Try another category, shop or search term.':'New products will appear here soon. Please check back later.'}</p><Button variant="outline" onClick={()=>{setCategory('all');setShop('all');setQuery('')}}>Clear filters</Button></div>:<div className="market-grid">{visible.map(p=><article className="market-product" key={p.key}><button className="market-product-art" onClick={()=>{setDetail(p);setImageIndex(0)}} aria-label={`View ${p.name}`}><Art p={p}/><span className={p.stock?'market-stock':'market-stock sold'}>{p.stock?`${p.stock} available`:'Sold out'}</span>{p.images?.length>1&&<span className="image-count">{p.images.length} photos</span>}</button><div className="market-product-meta"><span>{p.shop_name}</span><span>{p.category}</span></div><button className="market-product-name" onClick={()=>{setDetail(p);setImageIndex(0)}}>{p.name}</button><p>{p.variant||p.brand||'Standard'}</p><div className="market-product-price"><strong>{money(p.price)}</strong><Button variant="outline" size="sm" disabled={!p.stock||!!error} onClick={()=>add(p)} aria-label={`Add ${p.name} to bag`}><Plus size={16}/><span>Add</span></Button></div><small>{p.tax_rate?`+ ${p.tax_rate}% tax at checkout`:'No additional tax'}</small></article>)}</div>}</section></>}
 {view==='orders'&&<section className="customer-section"><p className="eyebrow">YOUR PURCHASES</p><h1>My orders</h1><p>Follow each shop’s order from confirmation to delivery.</p>{!user?<a className="auth-primary" href="/login">Sign in to view orders</a>:<>{ordersError&&<div className="error-banner">{ordersError}<Button onClick={loadOrders}>Retry</Button></div>}{!orders.length&&!ordersError&&<div className="market-empty"><Package/><h3>No orders yet</h3><p>Your orders will appear here after checkout.</p><Button onClick={()=>setView('browse')}>Explore the collection</Button></div>}{orders.map(o=><article className="customer-order" key={o.workspace+o.id}><header><div><small>{o.shop_name}</small><h3>{o.number}</h3><span>{fmt(o.at)}</span></div><span className={`pill ${['Cancelled','Returned'].includes(o.status)?'red':'green'}`}>{o.status}</span></header><div className="customer-order-body"><div><b>{o.lines.map((l:any)=>`${l.qty} × ${l.name}`).join(', ')}</b><p>{o.address}</p>{o.trackingNumber&&<p>Courier: {o.courier} · Tracking: {o.trackingNumber}</p>}</div><strong>{money(o.total)}</strong></div><div className="order-progress">{['Pending','Processing','Shipped','Completed'].map((st,i)=><span key={st} className={!['Cancelled','Returned'].includes(o.status)&&i<=['Pending','Processing','Shipped','Completed'].indexOf(o.status)?'done':''}><span/>{st}</span>)}</div><footer><Button variant="outline" onClick={()=>setOrderDetail(o)}>View order</Button>{o.status==='Pending'&&<Button variant="ghost" onClick={()=>setCancelOrder(o)}>Cancel order</Button>}</footer></article>)}</>}</section>}
 {view==='profile'&&<section className="customer-section"><p className="eyebrow">YOUR ACCOUNT</p><h1>My profile</h1>{user?<CustomerProfile user={user} setUser={setUser}/>:<div className="panel settings-card"><UserRound size={32}/><h2>Your customer profile</h2><p>Save your contact details and delivery address, manage your password, and follow your orders.</p><div className="dialog-actions"><a className="auth-secondary" href="/login">Sign in</a><a className="auth-primary" href="/signup">Create customer account</a></div></div>}</section>}
 </main><footer className="market-footer"><div><a href="/" className="market-brand"><Store size={22}/>ShopLink</a><p>Your local shops, connected.</p></div><div><button onClick={()=>setView('profile')}>My profile</button><button onClick={()=>setView('orders')}>My orders</button></div><p>Pay on delivery · Shipping is coordinated by each shop.<br/>Prices in LKR. Delivery charges: LKR 0 in this project version.</p></footer>
 <Sheet open={cartOpen} onOpenChange={setCartOpen}><SheetContent className="market-bag"><SheetHeader><SheetTitle>Your shopping bag <span>({units})</span></SheetTitle><SheetDescription>Orders are prepared separately by each shop.</SheetDescription></SheetHeader><div className="market-bag-items">{!cart.length?<div className="market-empty"><ShoppingBag/><h3>Your bag is empty</h3><p>Find something you love and add it here.</p></div>:lines.map(c=><div className="bag-line" key={c.key}><div className="bag-art">{c.product?<Art p={c.product}/>:<Package/>}</div><div className="bag-info"><small>{c.product?.shop_name||'Unavailable'}</small><b>{c.product?.name||c.name}</b><small>{c.product?.variant}</small><strong>{money((c.product?.price||0)*c.qty)}</strong>{(!c.product||c.qty>c.product.stock)&&<p className="negative">{c.product?`Only ${c.product.stock} available`:'No longer available'}</p>}<div className="quantity"><button aria-label="Decrease quantity" onClick={()=>setCart(items=>items.flatMap(x=>x.key===c.key?x.qty>1?[{...x,qty:x.qty-1}]:[]:[x]))}><Minus size={14}/></button><span>{c.qty}</span><button aria-label="Increase quantity" disabled={!c.product||c.qty>=c.product.stock} onClick={()=>add(c.product)}><Plus size={14}/></button></div></div><button aria-label={`Remove ${c.name}`} onClick={()=>setCart(items=>items.filter(x=>x.key!==c.key))}><X size={17}/></button></div>)}</div><div className="bag-summary"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>Tax</span><b>{money(tax)}</b></div><div><span>Delivery</span><span>Free</span></div><div className="bag-grand"><b>Total</b><b>{money(subtotal+tax)}</b></div><Button disabled={!cart.length||invalid||busy||!!error} onClick={startCheckout}>{user?'Continue to checkout':'Sign in to checkout'}<ArrowRight size={17}/></Button><small>Stock is confirmed when your order is placed.</small></div></SheetContent></Sheet>
 <Dialog open={!!detail} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="market-product-dialog"><DialogHeader className="sr-only"><DialogTitle>{detailNow?.name}</DialogTitle><DialogDescription>Product details and available stock</DialogDescription></DialogHeader>{detailNow&&<div className="product-detail-grid"><div><div className="detail-photo"><Art p={detailNow} index={imageIndex}/></div>{detailNow.images?.length>1&&<div className="detail-thumbs">{detailNow.images.map((src:string,i:number)=><button className={i===imageIndex?'selected':''} key={src+i} aria-label={`View image ${i+1}`} onClick={()=>setImageIndex(i)}><img src={src} alt=""/></button>)}</div>}</div><div className="detail-copy"><p className="eyebrow">{detailNow.category} · {detailNow.brand}</p><h2>{detailNow.name}</h2><p>{detailNow.variant||'Standard'}</p><strong>{money(detailNow.price)}</strong><small>{detailNow.tax_rate?`+ ${detailNow.tax_rate}% tax at checkout`:'No additional tax'}</small><div className="detail-availability"><span className="status-dot"/>{detailNow.stock} units available</div><p className="detail-description">{detailNow.description||'The shop has not added a description yet.'}</p><Button disabled={!detailNow.stock||!products.some(p=>p.key===detailNow.key)||!!error} onClick={()=>{add(detailNow);setDetail(null);setCartOpen(true)}}><ShoppingBag size={18}/>Add to bag</Button><div className="detail-shop"><Store size={23}/><div><b>{detailNow.shop_name}</b><small><MapPin size={12} className="inline"/> {detailNow.shop_city}</small><p>{detailNow.shop_description}</p>{detailNow.shop_phone&&<small>Shop contact: {detailNow.shop_phone}</small>}</div></div><small>SKU: {detailNow.sku}</small></div></div>}</DialogContent></Dialog>
 <Dialog open={checkout} onOpenChange={v=>{if(!busy)setCheckout(v)}}><DialogContent><DialogHeader><DialogTitle>Where should we deliver?</DialogTitle><DialogDescription>Cash on delivery. Each shop will prepare its items separately.</DialogDescription></DialogHeader><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const d=await post('/api/store/orders',{name:delivery.name,phone:delivery.phone,address:delivery.address,lines:lines.map(c=>({key:c.key,qty:c.qty,expectedPrice:c.product?.price,expectedTax:c.product?.tax_rate}))},{'Idempotency-Key':checkoutId});toast.success(`${d.orders.length} shop order${d.orders.length===1?'':'s'} placed`);setCart([]);setCheckout(false);setCartOpen(false);setView('orders');await loadCatalog();await loadOrders()}catch(e:any){toast.error(e.message);await loadCatalog()}finally{setBusy(false)}}}><div className="form-grid">{[['name','Full name'],['phone','Phone']].map(([key,label])=><label className="field" key={key}><span>{label}</span><Input required value={delivery[key]||''} onChange={e=>setDelivery((d:any)=>({...d,[key]:e.target.value}))}/></label>)}<label className="field full"><span>Complete delivery address</span><textarea required value={delivery.address||''} onChange={e=>setDelivery((d:any)=>({...d,address:e.target.value}))}/></label></div><div className="checkout-total"><span>Pay on delivery</span><b>{money(subtotal+tax)}</b></div><div className="dialog-actions"><Button type="button" variant="outline" disabled={busy} onClick={()=>setCheckout(false)}>Back</Button><Button disabled={busy||invalid||!!error}>{busy?'Placing your order…':'Place order'}</Button></div></form></DialogContent></Dialog>
 <Dialog open={!!orderDetail} onOpenChange={v=>{if(!v)setOrderDetail(null)}}><DialogContent className="customer-order-dialog"><DialogHeader><DialogTitle>{orderDetail?.number}</DialogTitle><DialogDescription>{orderDetail?.shop_name} · {orderDetail?.status}</DialogDescription></DialogHeader>{orderDetail&&<><p>{orderDetail.customer}<br/>{orderDetail.phone}<br/>{orderDetail.address}</p>{orderDetail.lines.map((l:any)=><div className="order-detail-line" key={l.id}><div><b>{l.name}</b><small>{l.variant} · {l.sku}</small></div><span>{l.qty} × {money(l.price)}</span></div>)}<dl><dt>Subtotal</dt><dd>{money(orderDetail.subtotal)}</dd><dt>Tax</dt><dd>{money(orderDetail.tax)}</dd><dt>Total</dt><dd><b>{money(orderDetail.total)}</b></dd><dt>Payment</dt><dd>{orderDetail.payment}</dd></dl>{orderDetail.trackingNumber&&<p>{orderDetail.courier} · {orderDetail.trackingNumber}</p>}</>}</DialogContent></Dialog>
 <Dialog open={!!cancelOrder} onOpenChange={v=>{if(!v)setCancelOrder(null)}}><DialogContent><DialogHeader><DialogTitle>Cancel this order?</DialogTitle><DialogDescription>{cancelOrder?.number} from {cancelOrder?.shop_name}. Its items will be returned to available stock.</DialogDescription></DialogHeader><div className="dialog-actions"><Button variant="outline" disabled={busy} onClick={()=>setCancelOrder(null)}>Keep order</Button><Button disabled={busy} onClick={async()=>{setBusy(true);try{await post('/api/store/cancel',{id:cancelOrder.id,workspace:cancelOrder.workspace});setCancelOrder(null);await loadOrders();await loadCatalog();toast.success('Order cancelled')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}>Confirm cancellation</Button></div></DialogContent></Dialog>
 </div>
}
function CustomerProfile({user,setUser}:any){const [f,setF]=useState({fullName:user.full_name,phone:user.phone,address:user.address}),[password,setPassword]=useState({currentPassword:'',newPassword:''}),[busy,setBusy]=useState(false);return <div className="customer-profile-grid"><section className="panel settings-card"><h2>Contact & delivery details</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const d=await post('/api/store/profile',f);setUser(d.user);toast.success('Profile saved')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><div className="form-grid">{[['fullName','Full name'],['phone','Phone'],['address','Default delivery address']].map(([k,label])=><label className="field full" key={k}><span>{label}</span><Input required={k!=='address'} value={(f as any)[k]} onChange={e=>setF(v=>({...v,[k]:e.target.value}))}/></label>)}<label className="field full"><span>Email</span><Input readOnly value={user.email}/></label></div><Button disabled={busy}>Save profile</Button></form></section><section className="panel settings-card"><h2>Password & account</h2><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{await post('/api/auth/password',{...password,kind:'customer'});setPassword({currentPassword:'',newPassword:''});toast.success('Password updated. Other sessions were signed out.')}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}}><div className="form-grid"><label className="field full"><span>Current password</span><Input type="password" required autoComplete="current-password" value={password.currentPassword} onChange={e=>setPassword(v=>({...v,currentPassword:e.target.value}))}/></label><label className="field full"><span>New password (10+ characters)</span><Input type="password" required minLength={10} maxLength={128} autoComplete="new-password" value={password.newPassword} onChange={e=>setPassword(v=>({...v,newPassword:e.target.value}))}/></label></div><Button disabled={busy} variant="outline">Change password</Button></form><button className="customer-signout" onClick={async()=>{await post('/api/auth/logout',{kind:'customer'});window.location.href='/'}}><LogOut size={16}/>Sign out</button></section></div>}
